---
- hosts: jumpbox
  gather_facts: true
  roles:
  - name: osp-facts

- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lbs, haproxy]}

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}

- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - {name: base-config, tags: base-config}
    - {name: geerlingguy.postgresql, tags: [dbs, postgres]}

- name: verify 3TA deployment
  hosts: jumpbox
  tasks:
    - name: connection test to frontend
      uri:
        url: "http://{{ hostvars[ item ]['inventory_hostname']}}"
        return_content: yes
      with_items:
        - "{{ groups['frontends']}}"
      register: webpage
      delegate_to: jumpbox

    - name: Fail if 'Ansible' string is not in the page content
      fail:
        msg: "Smoke test failed! Services were not accessible."
      when: "'Ansible' not in webpage.results[0].content"